name: Fetch Solved Problems

on:
  workflow_run:
    workflows: ["LeetCode Login"]  # 로그인 워크플로우가 성공적으로 완료된 후 실행
    types:
      - completed

jobs:
  fetch_problems:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # 레포지토리 코드를 가져옴

    - name: Set up Node.js and install leetcode-cli
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - run: npm install -g leetcode-cli  # LeetCode CLI 설치

    - name: Fetch list of solved problems
      run: |
        echo "Fetching solved problems..."
        leetcode list --status=solved --json > solved_problems.json  # 풀었던 문제 목록을 JSON으로 저장
      continue-on-error: false  # 문제 목록 추출 실패 시 워크플로우 중단
