name: LeetCode Sync

on:
  schedule:
    - cron: "0 0 * * *"  # 매일 자정 UTC에 실행
  workflow_dispatch:  # 수동으로 실행할 수 있는 옵션

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # GitHub PAT 사용

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install requirements
        run: pip install requests leetcode-export  # 필요한 패키지 설치

      - name: Run LeetCode sync script
        run: |
          leetcode-export --cookies "csrftoken=${{ secrets.CSRF_TOKEN }};LEETCODE_SESSION=${{ secrets.LEETCODE_SESSION }}" --only-accepted --only-last-submission --language=python --problem-folder-name "${difficulty}/${title_slug}"
        env:
          LEETCODE_SESSION: ${{ secrets.LEETCODE_SESSION }}  # LeetCode 세션 쿠키
          CSRF_TOKEN: ${{ secrets.CSRF_TOKEN }}  # CSRF 토큰

      - name: Commit and push changes
        run: |
          git config --local user.name "${{ secrets.GIT_USER_NAME }}"
          git config --local user.email "${{ secrets.GIT_USER_EMAIL }}"
          git add -A
          if git diff-index --quiet HEAD; then
            echo "No new changes to commit."
          else
            git commit -m "chore: sync LeetCode solutions"
            git push https://x-access-token:${{ secrets.LEETCODE_PAT }}@github.com/${{ github.repository }}.git
          fi
        env:
          LEETCODE_PAT: ${{ secrets.LEETCODE_PAT }}  # PAT 사용
