name: LeetCode Login with GitHub Token

on:
  workflow_dispatch:  # 수동 실행 가능
  schedule:
    - cron: '0 1 * * *'  # 매일 1시에 실행

jobs:
  login:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # 레포지토리 코드를 가져옴

    - name: Set up Node.js and install leetcode-cli
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - run: npm install -g leetcode-cli  # LeetCode CLI 설치

    - name: Login with GitHub Personal Access Token
      run: |
        echo "Logging in to LeetCode using GitHub Personal Access Token..."
        leetcode user --login-with-github-token ${{ secrets.GITHUB_TOKEN }}  # GitHub 토큰을 사용하여 로그인
      continue-on-error: false  # 로그인 실패 시 워크플로우 중단

    - name: Verify LeetCode login status
      run: |
        echo "Verifying login status..."
        leetcode user  # 로그인 상태를 확인하는 명령어
      continue-on-error: false  # 로그인 확인 실패 시 워크플로우 중단
